id: 9639c60337794c3c8ebd743981e461a4
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_218-Purification_of_Karmic_Obscurations-v1
  language: en
  author: ''
  volume: {}
